############################################
# Builder Stage
############################################

FROM node:24 AS builder

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

############################################
# Runner Stage
############################################

FROM node:24-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production

COPY --from=builder /app/package*.json ./

RUN npm ci --omit=dev

COPY --from=builder /app/src ./src
COPY --from=builder /app/drizzle ./drizzle

EXPOSE 8002

CMD ["node", "src/index.js"]